// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2x7szQ11U8V5yETiM7p5KeyHVo39FlY0',
    appId: '1:1077659105469:web:89889c0c68fa7acf00dfd4',
    messagingSenderId: '1077659105469',
    projectId: 'bscb-passs',
    authDomain: 'bscb-passs.firebaseapp.com',
    storageBucket: 'bscb-passs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYYcbjfyzHeE4T40gKh8BYwTxfL0vIHcM',
    appId: '1:1077659105469:android:c06bc2bbb482f86a00dfd4',
    messagingSenderId: '1077659105469',
    projectId: 'bscb-passs',
    storageBucket: 'bscb-passs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLmvtv5FFYw9gXWtgaB05r283ER6ZFzQE',
    appId: '1:1077659105469:ios:aad31e471c20a07d00dfd4',
    messagingSenderId: '1077659105469',
    projectId: 'bscb-passs',
    storageBucket: 'bscb-passs.appspot.com',
    iosBundleId: 'com.example.bscb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLmvtv5FFYw9gXWtgaB05r283ER6ZFzQE',
    appId: '1:1077659105469:ios:ab92739f960eb6f600dfd4',
    messagingSenderId: '1077659105469',
    projectId: 'bscb-passs',
    storageBucket: 'bscb-passs.appspot.com',
    iosBundleId: 'com.example.bscb.RunnerTests',
  );
}
